<a href="https://colab.research.google.com/github/kousikuppalapati/Machine-Learning-Lab/blob/main/MLWeek3(b).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#load the dataset
df=pd.read_csv('/content/cardata - cardata.csv')

In [ ]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [ ]:
df.describe()

              Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [ ]:
df.shape

(301, 9)

In [ ]:
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [ ]:
#count occurance of each Fuel_type in the dataset
df['Fuel_Type'].value_counts()

Fuel_Type
Petrol    239
Diesel     60
CNG         2
Name: count, dtype: int64

In [ ]:
#count occurance of each Seller_type in the dataset
df['Seller_Type'].value_counts()

Seller_Type
Dealer        195
Individual    106
Name: count, dtype: int64

In [ ]:
#count occurance of each Transmssion in the dataset
df['Transmission'].value_counts()

Transmission
Manual       261
Automatic     40
Name: count, dtype: int64

In [ ]:
#one hot encoding
df=pd.get_dummies(df,columns=['Fuel_Type','Seller_Type','Transmission'])

In [ ]:
df.columns

Index(['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Kms_Driven',
       'Owner', 'Fuel_Type_CNG', 'Fuel_Type_Diesel', 'Fuel_Type_Petrol',
       'Seller_Type_Dealer', 'Seller_Type_Individual',
       'Transmission_Automatic', 'Transmission_Manual'],
      dtype='object')

In [ ]:
#create feature matrix x b dropping car_name and selling-price columns
X=df.drop(['Car_Name','Selling_Price'],axis=1)
print("Feature matrix X created by dropping 'car_name' and 'selling_price' columns")

Feature matrix X created by dropping 'car_name' and 'selling_price' columns

In [ ]:
#select target vector Y containing the selling_price column
Y=df['Selling_Price']
print("Target vector Y created by selecting 'selling_price' column")

Target vector Y created by selecting 'selling_price' column

In [ ]:
X.head()

,Year,Present_Price,Kms_Driven,Owner,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
0,2014,5.59,27000,0,False,False,True,True,False,False,True
1,2013,9.54,43000,0,False,True,False,True,False,False,True
2,2017,9.85,6900,0,False,False,True,True,False,False,True
3,2011,4.15,5200,0,False,False,True,True,False,False,True
4,2014,6.87,42450,0,False,True,False,True,False,False,True

In [ ]:
Y.head()

0    3.35
1    4.75
2    7.25
3    2.85
4    4.60
Name: Selling_Price, dtype: float64

In [ ]:
#split the dataset into training and testing
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
print("Dataset split into training and testing sets")

Dataset split into training and testing sets

In [ ]:
#create model
model=LinearRegression()
print("Linear regression model created")

Linear regression model created

In [ ]:
#train the model
model.fit(X_train,Y_train)
print("Model trained on training data")

Model trained on training data

In [ ]:
#Generate predictions for training and testing data
Y_train_pred=model.predict(X_train)
Y_test_pred=model.predict(X_test)
print("Predictions generated for training and testing data")

Predictions generated for training and testing data

In [ ]:
#Evaluate the model performance on training data using metrics
train_mae=mean_absolute_error(Y_train,Y_train_pred)
train_mse=mean_squared_error(Y_train,Y_train_pred)
train_rmse=np.sqrt(train_mse)
train_r2=r2_score(Y_train,Y_train_pred)
print("Training metrics:")
print("Mean Absolute Error:",train_mae)
print("Mean Squared Error:",train_mse)
print("Root Mean Squared Error:",train_rmse)
print("R-squared:",train_r2)

Training metrics:
Mean Absolute Error: 1.1675804448342353
Mean Squared Error: 2.9437205399630173
Root Mean Squared Error: 1.7157274084081706
R-squared: 0.8886517300804558

In [ ]:
##Evaluate the model performance on testing data using metrics
test_mae=mean_absolute_error(Y_test,Y_test_pred)
test_mse=mean_squared_error(Y_test,Y_test_pred)
test_rmse=np.sqrt(test_mse)
test_r2=r2_score(Y_test,Y_test_pred)
print("Testing metrics:")
print("Mean Absolute Error:",test_mae)
print("Mean Squared Error:",test_mse)
print("Root Mean Squared Error:",test_rmse)
print("R-squared:",test_r2)

Testing metrics:
Mean Absolute Error: 1.216225682130144
Mean Squared Error: 3.4788039706448317
Root Mean Squared Error: 1.8651552135532399
R-squared: 0.8489813024896058

In [ ]:
#coefficient and Intercept
print("Slope:",model.coef_)
print("Intercept:",model.intercept_)

Slope: [ 3.53801365e-01  4.29152503e-01 -6.15725866e-06 -9.03759824e-01
 -1.09057894e+00  1.44269365e+00 -3.52114710e-01  5.95296453e-01
 -5.95296453e-01  8.19510777e-01 -8.19510777e-01]
Intercept: -710.2771513359723